//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChuyenBay
    {
        public int STT { get; set; }
        public string MaCTCB { get; set; }
        public string SanBayTrungGian { get; set; }
        public string ThoiGianDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
    }
}
