//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuNam
    {
        public string MaDTNam { get; set; }
        public string MaDTThang { get; set; }
        public Nullable<int> SoLuongVeBan { get; set; }
        public Nullable<double> DoanhThu { get; set; }
    
        public virtual DoanhThuThang DoanhThuThang { get; set; }
    }
}
