//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookingAirLightEntities : DbContext
    {
        public BookingAirLightEntities()
            : base("name=BookingAirLightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietChuyenBay> ChiTietChuyenBays { get; set; }
        public virtual DbSet<ChiTietHD> ChiTietHDs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<ChuyenBay> ChuyenBays { get; set; }
        public virtual DbSet<DoanhThuNam> DoanhThuNams { get; set; }
        public virtual DbSet<DoanhThuThang> DoanhThuThangs { get; set; }
        public virtual DbSet<HangVe> HangVes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiKH> LoaiKHs { get; set; }
        public virtual DbSet<MayBay> MayBays { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Phi> Phis { get; set; }
        public virtual DbSet<PhieuDatCho> PhieuDatChoes { get; set; }
        public virtual DbSet<SanBay> SanBays { get; set; }
        public virtual DbSet<TuyenBay> TuyenBays { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
        public virtual DbSet<save_log_chuyenbay> save_log_chuyenbay { get; set; }
    
        public virtual int sp_Hoanve(string mave, string macb)
        {
            var maveParameter = mave != null ?
                new ObjectParameter("mave", mave) :
                new ObjectParameter("mave", typeof(string));
    
            var macbParameter = macb != null ?
                new ObjectParameter("macb", macb) :
                new ObjectParameter("macb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Hoanve", maveParameter, macbParameter);
        }
    
        public virtual int sp_XoaPDC(string macb, string soghe)
        {
            var macbParameter = macb != null ?
                new ObjectParameter("macb", macb) :
                new ObjectParameter("macb", typeof(string));
    
            var sogheParameter = soghe != null ?
                new ObjectParameter("soghe", soghe) :
                new ObjectParameter("soghe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPDC", macbParameter, sogheParameter);
        }
    
        public virtual int sp_Hoanve1(string mahd)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Hoanve1", mahdParameter);
        }
    }
}
