//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public string IDUser { get; set; }
        public string MaCBdi { get; set; }
        public string MaCBve { get; set; }
        public string Status { get; set; }
    }
}
