//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class save_log_chuyenbay
    {
        public System.DateTime Malog { get; set; }
        public string ThaoTac { get; set; }
        public string MaCB { get; set; }
        public string MaMB { get; set; }
        public string MaTBay { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
        public string ThoiGianBay { get; set; }
    }
}
