//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public string MaWL { get; set; }
        public string MaCB { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public string MaCBVe { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
